version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-daytechstagram:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daytechstagram
volumes:
  postgres-daytechstagram: